== Obliczanie złożoności cyklicznej
=== Na podstawie https://radon.readthedocs.io/en/latest/intro.html#cyclomatic-complexity[dokumentacji] narzędzia Radon
[options="header"]

*Cyclomatic Complexity* corresponds to the number of decisions a block of code contains plus 1.
|=======================
|Construct        |Efect on CC     |Reasoning
|if               |+1              |An _if_ statement is a single decision.
|elseif           |+1              |The _elif_ statement adds another decision.
|else             |+0              |The _else_ statement does not cause a new decision. The decision is at the _if_.
|for              |+1              |There is a decision at the start of the loop.
|while            |+1              |There is a decision at the _while_ statement.
|except           |+1              |Each _except_ branch adds a new conditional path of execution.
|finally          |+0              |The _finally_ block is unconditionally executed.
|with             |+1              |The _with_ statement roughly corresponds to a try/except block (see PEP 343 for details).
|assert           |+1              |The _assert_ statement internally roughly equals a conditional statement.
|Comprehension    |+1              |A list/set/dict comprehension of generator expression is equivalent to a for loop.
|Boolean Operator |+1              |Every boolean operator (and, or) adds a decision point.
|=======================

.file.py
```python
class Bird(object):
  name = ''
  flightless = False
  extinct = False

  def get_speed(self):                  # 10 = 1 +
    if self.extinct:                    # 1 +
      return -1 # we do not care about extinct bird speeds
    else:
      if self.flightless:               # 1 +
        if self.name == 'Ostrich':      # 1 +
          return 15
        elif self.name == 'Chicken':    # 1 +
          return 7
        elif self.name == 'Flamingo':   # 1 +
          return 8
        else:
          return -1 # bird name not implemented
      else:
        if self.name == 'Gold Finch':   # 1 +
          return 12
        elif self.name == 'Bluejay':    # 1 +
          return 10
        elif self.name == 'Robin':      # 1 +
          return 14
        elif self.name == 'Hummingbird':  # 1
          return 16
        else:
          return -1 # bird not implemented
```

```sh
radon cc -s python_files/file.py
    python_files/file.py
        C 1:0 Bird - B (10)
        M 6:2 Bird.get_speed - B (10)
```