== Obliczanie złożoności cyklicznej
=== Na podstawie https://radon.readthedocs.io/en/latest/intro.html#cyclomatic-complexity[dokumentacji] narzędzia Radon
[options="header"]

*Cyclomatic Complexity* corresponds to the number of decisions a block of code contains plus 1.
|=======================
|Construct        |Efect on CC     |Reasoning
|if               |+1              |An _if_ statement is a single decision.
|elseif           |+1              |The _elif_ statement adds another decision.
|else             |+0              |The _else_ statement does not cause a new decision. The decision is at the _if_.
|for              |+1              |There is a decision at the start of the loop.
|while            |+1              |There is a decision at the _while_ statement.
|except           |+1              |Each _except_ branch adds a new conditional path of execution.
|finally          |+0              |The _finally_ block is unconditionally executed.
|with             |+1              |The _with_ statement roughly corresponds to a try/except block (see PEP 343 for details).
|assert           |+1              |The _assert_ statement internally roughly equals a conditional statement.
|Comprehension    |+1              |A list/set/dict comprehension of generator expression is equivalent to a for loop.
|Boolean Operator |+1              |Every boolean operator (and, or) adds a decision point.
|=======================

.file.py
```python
class Bird(object):
  name = ''
  flightless = False
  extinct = False

  def get_speed(self):                  # 10 = 1 +
    if self.extinct:                    # 1 +
      return -1 # we do not care about extinct bird speeds
    else:
      if self.flightless:               # 1 +
        if self.name == 'Ostrich':      # 1 +
          return 15
        elif self.name == 'Chicken':    # 1 +
          return 7
        elif self.name == 'Flamingo':   # 1 +
          return 8
        else:
          return -1 # bird name not implemented
      else:
        if self.name == 'Gold Finch':   # 1 +
          return 12
        elif self.name == 'Bluejay':    # 1 +
          return 10
        elif self.name == 'Robin':      # 1 +
          return 14
        elif self.name == 'Hummingbird':  # 1
          return 16
        else:
          return -1 # bird not implemented
```

```sh
radon cc -s python_files/file.py
    python_files/file.py
        C 1:0 Bird - B (10)
        M 6:2 Bird.get_speed - B (10)
```

```sh
pylint lab3/python_files/file.py

  ************* Module file
  W:  2, 0: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
  W:  3, 0: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
  W:  4, 0: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
  W:  6, 0: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
  W:  7, 0: Bad indentation. Found 4 spaces, expected 8 (bad-indentation)
  W:  8, 0: Bad indentation. Found 6 spaces, expected 12 (bad-indentation)
  W:  9, 0: Bad indentation. Found 4 spaces, expected 8 (bad-indentation)
  W: 10, 0: Bad indentation. Found 6 spaces, expected 12 (bad-indentation)
  W: 11, 0: Bad indentation. Found 8 spaces, expected 16 (bad-indentation)
  W: 12, 0: Bad indentation. Found 10 spaces, expected 20 (bad-indentation)
  W: 13, 0: Bad indentation. Found 8 spaces, expected 16 (bad-indentation)
  W: 14, 0: Bad indentation. Found 10 spaces, expected 20 (bad-indentation)
  W: 15, 0: Bad indentation. Found 8 spaces, expected 16 (bad-indentation)
  W: 16, 0: Bad indentation. Found 10 spaces, expected 20 (bad-indentation)
  W: 17, 0: Bad indentation. Found 8 spaces, expected 16 (bad-indentation)
  W: 18, 0: Bad indentation. Found 10 spaces, expected 20 (bad-indentation)
  W: 19, 0: Bad indentation. Found 6 spaces, expected 12 (bad-indentation)
  W: 20, 0: Bad indentation. Found 8 spaces, expected 16 (bad-indentation)
  W: 21, 0: Bad indentation. Found 10 spaces, expected 20 (bad-indentation)
  W: 22, 0: Bad indentation. Found 8 spaces, expected 16 (bad-indentation)
  W: 23, 0: Bad indentation. Found 10 spaces, expected 20 (bad-indentation)
  W: 24, 0: Bad indentation. Found 8 spaces, expected 16 (bad-indentation)
  W: 25, 0: Bad indentation. Found 10 spaces, expected 20 (bad-indentation)
  W: 26, 0: Bad indentation. Found 8 spaces, expected 16 (bad-indentation)
  W: 27, 0: Bad indentation. Found 10 spaces, expected 20 (bad-indentation)
  W: 28, 0: Bad indentation. Found 8 spaces, expected 16 (bad-indentation)
  C: 29, 0: Final newline missing (missing-final-newline)
  W: 29, 0: Bad indentation. Found 10 spaces, expected 20 (bad-indentation)
  C:  1, 0: Missing module docstring (missing-docstring)
  C:  1, 0: Missing class docstring (missing-docstring)
  C:  6, 2: Missing method docstring (missing-docstring)
  R:  7, 4: Unnecessary "else" after "return" (no-else-return)
  R: 10, 6: Unnecessary "else" after "return" (no-else-return)
  R: 11, 8: Unnecessary "else" after "return" (no-else-return)
  R: 20, 8: Unnecessary "else" after "return" (no-else-return)
  R:  6, 2: Too many return statements (10/6) (too-many-return-statements)
  R:  1, 0: Too few public methods (1/2) (too-few-public-methods)

  ------------------------------------
  Your code has been rated at -5.42/10

```